spring:
  application:
    name: sample-logstash

server:
  port: ${API_PAYMENT_PORT:8080}

management:
  security:
    enabled: false

info:
  app:
    name: Gateway Sample Logstash
    description: Simulated Payment
    version: 1.0.0
    company: EWS
    author: Eduardo Wallace

#logging:
#  file: /Users/wallace/Apps/spring-cloud-netflix-demo/log/api-payment.log



